name: Dictyexpress-js CI

on:
  push:
    branches:
      - main
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4
      - name: Select Node v${{ matrix.node-version }}
        shell: bash -l {0}
        run: |
          nvm use ${{ matrix.node-version }}
          echo "PATH=$(echo $PATH)" >> "$GITHUB_ENV"
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT
      - name: Restore yarn cache
        uses: actions/cache@v4
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-cache-folder-${{ hashFiles('**/yarn.lock', '.yarnrc.yml') }}
          restore-keys: |
            yarn-cache-folder-
      - name: Install packages
        run: yarn
      - name: Install Playwright dependencies
        run: yarn playwright install chromium
      - name: Run Linters
        run: yarn lint
      - name: Run Tests
        run: yarn test
      - name: Run build
        run: yarn build
