name: Deploy - 01 SSH connectivity check

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  ssh-check:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Verify required secrets exist
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
        run: |
          missing=0
          [ -z "$VPS_HOST" ] && echo "::error::Missing secret VPS_HOST" && missing=1
          [ -z "$VPS_USER" ] && echo "::error::Missing secret VPS_USER" && missing=1
          [ -z "$VPS_SSH_KEY" ] && echo "::error::Missing secret VPS_SSH_KEY" && missing=1
          if [ "$missing" -eq 1 ]; then
            echo "One or more required secrets are missing. Please add them in GitHub repo Settings > Secrets and variables > Actions."
            exit 1
          fi

      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.VPS_SSH_KEY }}
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_SSH_PORT: ${{ secrets.VPS_SSH_PORT }}
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          port=${VPS_SSH_PORT:-22}
          ssh-keyscan -p "$port" -H "$VPS_HOST" >> ~/.ssh/known_hosts 2>/dev/null
          chmod 644 ~/.ssh/known_hosts

      - name: Test SSH connection
        env:
          VPS_HOST: ${{ secrets.VPS_HOST }}
          VPS_USER: ${{ secrets.VPS_USER }}
          VPS_SSH_PORT: ${{ secrets.VPS_SSH_PORT }}
        run: |
          port=${VPS_SSH_PORT:-22}
          ssh -o BatchMode=yes -o StrictHostKeyChecking=yes -p "$port" -i ~/.ssh/id_ed25519 "${VPS_USER}@${VPS_HOST}" 'echo "Connected as $(whoami) on $(hostname)" && uname -a'


